#version: '3.8'
services:
  postgres:
    image: postgres:16 # latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      #start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mynetwork

  backend:
    build:
      context: ./BACKEND
      dockerfile: dockerfile
    volumes:
      - ./BACKEND:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      #- postgres
    networks:
      - mynetwork
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: dockerfile
    environment:
      API_URL: http://backend:8000
    ports:
    - "8501:8501"
    depends_on:
    - backend
    networks:
    - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: