#version: '3.8'
services:
  postgres:
    image: postgres:16 # latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  backend:
    build:
      context: ./BACKEND
      dockerfile: dockerfile-backend
    volumes:
      - ./BACKEND:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres:5432/mydatabase
      #DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: